#include "sakhi_core.h"

/*
 * Minimal Sakhi implementation.
 * Produces a fixed response.
 * Future versions will add tone, language, clarity.
 */

L3Response sakhi_speak(const L3Request *request,
                       const NiyuResult *result)
{
    (void)request;
    (void)result;

    L3Response response;
    response.text = "L3 active. Response generated by Sakhi.";
    response.success = 1;
    return response;
}
